name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          # Workload Identity Provider Location
          workload_identity_provider: "projects/984300244589/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          # GitHub Service Account
          service_account: "github-actions-sa@cloud-functions-demo-359919.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "hello"               # Name of the Cloud Function
          description: 'A simple test function'
          runtime: "python310"        # Runtime to use for the function
          entry_point: "hello_world"  # Name of the entrypoint function in main.py
          memory_mb: 256              # Max 8GB. Defaults to 256MB
          source_dir: cloud-function-demo   # Where main.py is located.
          timeout: 60                # 540 max for 1st gen functions
          region: "europe-west2"      # London
          https_trigger_security_level: "secure_always" # HTTPS only
          # Service account to use to invoke the cloud function.
          service_account_email: github-actions-sa@cloud-functions-demo-359919.iam.gserviceaccount.com
          env_vars: |-
            VAR1="This is an environment variable"
          secret_environment_variables: |-
            SECRET1='projects/984300244589/secrets/my-secret/versions/1'
            

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
